"""Plot Verifier — a second AI that visually inspects each generated plot.

We send the plot image + the agent's stated RESULT line to Gemini 2.0 Flash
(multimodal) and ask whether the visual evidence supports the claim.

Output:
  Verdict: SUPPORTED | UNCLEAR | CONTRADICTED
  Visual: 1–2 sentences describing what's actually shown
  Note  : 1 sentence — agreement / disagreement reason
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from mlra.config import settings

VERIFIER_PROMPT = """You are a careful scientific plot reviewer. You will be shown a plot generated by an automated ML research agent, and the agent's stated RESULT line.

Your job: looking ONLY at the plot, decide whether the visual evidence supports the agent's claim.

Reply in EXACTLY this format (3 lines):

Verdict: SUPPORTED | UNCLEAR | CONTRADICTED
Visual: <1-2 sentences describing what the plot actually shows — values, trends, peaks>
Note: <1 sentence — does the visual agree with the claim? Be specific.>

Be terse. Be honest. If you can't tell, say UNCLEAR.
"""


@dataclass
class VerifierResult:
    verdict: str  # SUPPORTED | UNCLEAR | CONTRADICTED | ERROR
    visual: str
    note: str
    raw: str


def verify(plot_path: Path, claimed_result: str) -> VerifierResult:
    """Send plot image + claim to Gemini Flash; parse the structured reply."""
    if not settings.google_api_key:
        return VerifierResult(
            verdict="UNCLEAR",
            visual="(verifier disabled — no GOOGLE_API_KEY)",
            note="Add a free Gemini key at https://aistudio.google.com/app/apikey",
            raw="",
        )

    from google import genai
    from google.genai import types

    client = genai.Client(api_key=settings.google_api_key)
    image_bytes = plot_path.read_bytes()

    user_text = f"Agent's claim:\n{claimed_result}\n\nPlot ({plot_path.name}):"

    try:
        response = client.models.generate_content(
            model=settings.gemini_model,
            contents=[
                VERIFIER_PROMPT,
                user_text,
                types.Part.from_bytes(data=image_bytes, mime_type="image/png"),
            ],
        )
        text = (response.text or "").strip()
    except Exception as e:
        return VerifierResult("ERROR", "(verifier call failed)", str(e), "")

    return _parse(text)


def _parse(text: str) -> VerifierResult:
    """Parse the 3-line structured reply."""
    verdict = "UNCLEAR"
    visual = ""
    note = ""
    for line in text.splitlines():
        line = line.strip()
        if line.lower().startswith("verdict:"):
            payload = line.split(":", 1)[1].strip().upper()
            for keyword in ("SUPPORTED", "UNCLEAR", "CONTRADICTED"):
                if keyword in payload:
                    verdict = keyword
                    break
        elif line.lower().startswith("visual:"):
            visual = line.split(":", 1)[1].strip()
        elif line.lower().startswith("note:"):
            note = line.split(":", 1)[1].strip()

    if not visual and not note:
        # fallback if the model didn't follow format — keep the raw text
        note = text[:300]

    return VerifierResult(verdict=verdict, visual=visual, note=note, raw=text)


def extract_result_line(stdout_lines: list[str]) -> str:
    """Pull the agent's RESULT line out of stdout. Falls back to last 3 lines."""
    for line in reversed(stdout_lines):
        if line.strip().upper().startswith("RESULT:"):
            return line.strip()
    # fallback: best-effort summary
    tail = [ln for ln in stdout_lines[-5:] if ln.strip()]
    return " | ".join(tail) if tail else "(no RESULT line printed)"
